<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>WallJoiner.Geometry</AssemblyName>
    <RootNamespace>ProWallTools.Geometry</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GeometryTypes.fs" />
    <Compile Include="GeometryKernel.fs" />
    <Compile Include="LoopSimplifier.fs" />
  </ItemGroup>
</Project>
